env: testnet
urls:
  elrondApi: 'https://testnet-api.elrond.com/'
  swagger:
    - 'https://testnet-microservice.elrond.com'
    - 'https://devnet-microservice.elrond.com'
    - 'https://microservice.elrond.com'
  redis: '127.0.0.1'
  rabbitMqUrl: 'amqp://localhost:5672'
security:
  jwtSecret: ''